name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: latest

      - name: Build
        run: zig build

      - name: Test
        run: zig build test
